### ISSUE TITLE
BD support

### ISSUE THREAD

**Issue by Tropix126** [vaxx-y/protoncord#3]
Since the last issue was locked, I guess I have to make another issue. The theme itself appears to work fine on BD, however the source code needs to be sideloaded (screenshot below).
![image](https://user-images.githubusercontent.com/42101043/111022484-9f8cbb00-8398-11eb-850d-322a7067d6df.png)

The problem is simply that Github pages is not setup on this repo and therefore your import statement is running into a 404. Enabling GitHub pages on this repo should completely fix BD support.

**Comment by Tropix126** [comment]
As far as I know this theme uses no client-mod dependant features so it should run without any issues.

**Comment by vaxx-y** [comment]
I wasn't aware that changing my username makes the server return a 404. I thought that GitHub will properly redirect these requests but after checking again, they do not redirect the pages. This has been fixed in the last commit.
